runtime: custom
env: flex

# This section is optional if you want to specify manual scaling.
manual_scaling:
  instances: 1  # You can adjust the number of instances based on your needs.

resources:
  cpu: 4
  memory_gb: 16
  disk_size_gb: 20  # Adjusted to match your initial Cloud Run configuration
